name: latex-build
description: Build a LaTeX Document
author: Ondrej Sika
branding:
  icon: 'anchor'
  color: 'blue'
runs:
  using: docker
  image: docker://schickling/latex
  args:
    - pdflatex
    - ${{ inputs.filename }}
inputs:
  filename:
    required: true
    description: Username used to log in to a Docker registry. If not set then no login will occur

